### ISSUE TITLE
Erro fatal ao instalar

### ISSUE THREAD

**Issue by ESA55** [LinkNacional/payment-banking-slip-pix-for-lifterlms#4]
Ausência de arquivo ou diretório no endereço:
wp-content/plugins/payment-banking-slip-pix-for-lifterlms-main/public/class-lkn-payment-banking-slip-pix-for-lifterlms-slip.php on line 3

Wordpress versão: 6.3.1
Lifterlms versão: 7.4.0 (gratuita)

Servidor:

Mysql Version: 10.6.15

Php Curl: Yes

Php Default Timezone: UTC

Php Fsockopen: Yes

Php Max Input Vars: 100000

Php Max Upload Size: 1 GB

Php Memory Limit: 1024M

Php Post Max Size: 1024M

Php Soap: Yes

Php Suhosin: No

Php Time Limt: 300

Php Version: 8.2.9

Software: LiteSpeed

Wp Memory Limit: 40M

**Comment by FabricioQueirozLkn** [comment]
Olá, desculpe o atraso para responder, talvez já tenha conseguido solucionar o problema, mas vamos lá: 

A linha 3 mostrada no erro, é referente à inserção do diretório `/vendor/`, no caso a falta dele. Normalmente esse diretório seria gerado pelo comando `composer install`. Mas o diretório já está disponível no arquivo **payment-banking-slip-pix-for-lifterlms-updt.zip** da Release. 

Algumas soluções seriam:

* Baixar e instalar a Release novamente: https://github.com/LinkNacional/payment-banking-slip-pix-for-lifterlms/releases/tag/v1.0.0;

* Rodar o comando `composer install` manualmente para gerar o diretório `/vendor/`.

As notificações dessa _issue_ foram ativadas, então responderei o mais rápido possível. Desde já agradeço a paciência.

Atte. @FabricioQueirozLkn.
